platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target 'Awesome' do
    
    pod 'SwifterSwift'
    pod 'GestureRecognizerClosures'
    pod 'Reusable'
    pod 'SnapKit'
    pod 'ActionKit'
    
    # Tool
    pod 'SwiftLint'
    pod 'FLEX'
    pod 'MLeaksFinder', :configurations => ['Debug']

end
