platform :ios, '8.0'
inhibit_all_warnings!

source 'git@gitlab.cngump.com:ganguo_ios/GanguoRepo.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'yzwgo' do

pod 'AFNetworking', '~> 3.1.0'
pod 'GGCommonKit', :git => 'git@gitlab.cngump.com:ganguo_ios/ggcommonkit.git'
pod 'PureLayout', '~> 3.0.2'
pod 'FLEX', '~> 2.1.1'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'YYKit', '~> 1.0.9'
pod 'FlexibleAIFNetworking', '~> 1.0.7'
pod 'Bugly', '~> 2.4.7'
pod 'AVOSCloud', '~> 4.2.0'
pod 'AVOSCloudIM', '~> 4.2.0'
pod 'SDCycleScrollView', '~> 1.65'
pod 'HCSStarRatingView', '~> 1.5'
pod 'BEMCheckBox', '~> 1.4.0'
pod 'UITextView+Placeholder', '~> 1.2'
pod 'TPKeyboardAvoiding', '~> 1.3'
pod 'MJRefresh', '~> 3.1.0'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'PSTAlertController', '~> 1.2.0'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'INTULocationManager', '~> 4.2.0'
pod 'IDMPhotoBrowser', '~> 1.11.3'
pod 'TYAlertController', '~> 1.1.8'

pod 'GanguoServices/Component/FPSDisplay', '~> 0.1.10'
pod 'GanguoServices/Component/WeixinShare', '~> 0.1.10'
pod 'GanguoServices/Component/WeiboShare', '~> 0.1.10'
pod 'GanguoServices/Component/QQShare', '~> 0.1.10'
pod 'GanguoServices/Component/Alipay', '~> 0.1.10'

#local pod
pod 'ScanQRCode', :path => 'modules/ScanQRCode'

end

