platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target 'Demo' do
        
    # Tool
    pod 'SwiftLint'
    pod 'FLEX'

    # Sources dependency    
    pod 'SwifterSwift'    
    pod 'AlamofireImage'
    
    pod 'SnapKit'
    pod 'SwiftTimer'
    pod 'MBProgressHUD'    
    pod 'SwiftLocation'
    pod 'AXPhotoViewer'

end
